services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    ports:
      - "4000:4000"
    command: jekyll serve --force_polling --drafts --incremental

volumes:
  bundle:
